
menu:
- {name: 'Trivia',  url: 'facts'}
- {name: 'Teaching resources', url: 'resources'}
- {name: 'About',              url: 'about'}


# Customize site text
pagination:
  next_page: '->'
  previous_page: '<-'

related_posts: 'Related posts' #heading for links at bottom of page

post_date_prefix: '' #Used on post headers
